const translations = {
    "es": {
        "we-are-button": "Quiénes somos",
        "partners-button": "Socios",
        "services-button": "Nuestros servicios",
        "certifications-button": "Certificaciones",
        "contact-button": "Contacto",
        "ctechs-hero-title": "Líderes",
        "ctechs-hero-subtitle": "en tecnologías de la nube",
        "ctechs-hero-description": "Responsabilidad Honestidad Perseverancia",
        "ctechs-hero-secondslide-firsttitle": "instructores",
        "ctechs-hero-secondslide-secondtitle": "soporte",
        "ctechs-hero-secondslide-thirdtitle": "certificaciones",
        "whoweare-title": "quienes . somos",
        "whoweare-desc": "Somos una empresa con más de 10 años en el mercado dedicada a brindar servicios y soluciones de entrenamiento y consultoría basadas en plataformas en la nube como Amazon Web Services, Google Cloud Partner y CompTIA.<br><br>Buscando contribuir al desarrollo tecnológico de cada empresa, contamos con un equipo de ingenieros y entrenadores altamente capacitados y certificados.",
        "ourbenefits-title": "nuestros<br> <strong>beneficios</strong>",
        "personel-text": "<strong>Personal especializado</strong><br>en gestión de asignaciones y calendarios",
        "attention-text": "<strong>Atención personalizada</strong><br>a nivel de gestión",
        "specialists-text": "<strong>Especialistas asignados</strong><br>para atender las consultas de sus clientes",
        "acquisition": "<strong class='span-blue'>Adquisición y renovación</strong><br>plan para nuevas y existentes <strong class='span-blue'>certificaciones</strong> en el mercado",
        "real-time": "<strong class='span-blue'>Tiempo real</strong><br>equipo de soporte asignado a cada sesión",
        "dedicated": "<strong class='span-blue'>Aprendizaje y desarrollo dedicados</strong><br>proceso de habilidades andragógicas para cada instructor",
        "continous": "<strong class='span-blue'>Entrenamiento continuo</strong><br>sobre herramientas y plataformas de capacitación",
        "high-adaptability": "<strong class='span-blue'>Alta adaptabilidad</strong><br>a nuevas plataformas, metodologías, procesos y herramientas corporativas internas",
        "contactus-title": "Contáctanos",
        "contact-name-placeholder": "Tu nombre",
        "contact-email-placeholder": "Tu correo",
        "contact-phone-placeholder": "Tu teléfono",
        "send-request": "Enviar solicitud",
        "partners": "<strong>socios</strong>",
        "partners-text": "Ofrecemos instructores especializados a centros de formación<br> y socios de aprendizaje de todo el mundo.",
        "services-title": "nuestros<br> <strong>servicios</strong>",
        "services-highligth": "Contamos con <strong class='text-color-orange'>la mejor tecnología</strong> <span class='text-biggest'>&</span> <strong class='text-color-blue'>consultores certificados</strong> para ofrecerle servicios de calidad",
        "training-title": "Entrenamiento",
        "training-desc": "Contamos con instructores nativos y expertos en diferentes idiomas, como inglés, español, francés, portugués y otros. Avalados por diez años en el mercado, todos nuestros formadores están certificados.",
        "consulting-title": "Consultoria",
        "consulting-desc": "Ofrecemos soluciones de formación impartidas por expertos en el ámbito tecnológico que ayudan a la empresa y a sus empleados a mejorar sus competencias técnicas.",
        "managed-title": "Servicios Administrados",
        "managed-desc": "Ofrecemos soluciones de gestión de escritorios, servidores y dispositivos cliente que ayudan a nuestros clientes a reducir la complejidad de la gestión de la infraestructura así como de los servicios administrativos, acelerando el retorno de la inversión y proporcionando recursos que aseguren la correcta gestión de los servicios Cloud.",
        "cloud-title": "Implementación de tecnología en la nube",
        "cloud-desc": "Ofrecemos consultoría, administración e implementación de servicios en la nube, facilitando las plataformas de nuestros clientes, utilizando tecnologías de punta que nos posicionan como líderes en el mercado.",
        "certifications-title": "<strong>Certificaciones</strong>",
        /* Mstecs */
        "mstecs-header-contact": "Contacto",
        "callus": "Comunícate<br> +52 449 284 1532",
        "mailus": "Cotiza directamente<br> correo@mstecs.com",
        "mstecs-hero-title": "Líderes en tecnología",
        "mstecs-hero-list-item1": "Ventas",
        "mstecs-hero-list-item2": "Licenciamiento",
        "mstecs-hero-list-item3": "Consultoría",
        "mstecs-hero-list-item4": "Servicios administrados",
        "mstecs-hero-list-item5": "Presencia global",
        "mstecs-licensing-title": "Licenciamiento",
        "mstecs-licensing-subtitle": "Optimiza tu crecimiento con nuestras opciones",
        "m365desc": "Accede a las mejores herramientas de trabajo colaborativo, almacenamiento en la nube y más. Licencias a precios especiales.",
        "business-plan-btn": "Plan empresarial",
        "smb-plan-btn": "Planes PYME",
        "googledesc": "Potencia tu infraestructura con soluciones escalables, seguras y flexibles. Licencias disponibles a precios competitivos.",
        "plan-prices-btn": "Ver planes y precios",
        "plan-prices-btn2": "Ver planes y precios",
        "plan-prices-btn3": "Ver planes y precios",
        "azuredesc": "Obtén escalabilidad, seguridad y flexibilidad en la nube. Transforma tu negocio hoy.",
        "awsdesc": "Servicios en la nube líderes para escalar, innovar y proteger tu empresa con soluciones flexibles y seguras.",
        "mstecs-services-title": "Servicios",
        "mstecs-services-subtitle": "Somos socios Microsoft por lo que nuestros entrenadores están altamente capacitados.",
        "mstecs-allies-title": "Nuestros aliados",
        /*Microsoft*/
        "mstecs-features-title-microsoft": "PLANES PYME",
        "application": "APLICACIONES",
        "basic": "Empresa Básico",
        "standard": "Empresa Estándar",
        "premium": "Empresa Premium",
        "for-busisness": "para negocios",
        "from": "DESDE",
        "from2": "DESDE",
        "from3": "DESDE",
        "from4": "DESDE",
        "per-user": "por usuario al mes",
        "per-user2": "por usuario al mes",
        "per-user3": "por usuario al mes",
        "per-user4": "por usuario al mes",
        "anual-month": "(Planes anuales y mensuales adaptados a tus necesidades)",
        "anual-month2": "(Planes anuales y mensuales adaptados a tus necesidades)",
        "anual-month3": "(Planes anuales y mensuales adaptados a tus necesidades)",
        "anual-month4": "(Planes anuales y mensuales adaptados a tus necesidades)",
        "quote": "Cotizar ahora",
        "quote2": "Cotizar ahora",
        "quote3": "Cotizar ahora",
        "quote4": "Cotizar ahora",
        "app-first-start": "Aplicaciones y servicios para poner en marcha tu negocio, entre los que se incluyen:",
        "basic-list": "<li>Administración de identidades, accesos y usuarios para hasta 300 empleados</li><li>Correo empresarial personalizado (tú@tunegocio.com)</li><li>Versiones web y móviles de Word, Excel, PowerPoint y Outlook</li><li>Chats, llamadas y videoconferencias con Microsoft Teams</li><li>1 TB de almacenamiento en la nube por empleado</li><li>Más de 10 aplicaciones adicionales para tus necesidades empresariales (Microsoft Bookings, Planner, Forms y otras)</li><li>Filtrado automático de correo no deseado y malware</li><li>Soporte ininterrumpido por teléfono y a través de la Web</li><li>Microsoft 365 Copilot está disponible como complemento</li>",
        "secure-services": "Servicios seguros en la nube:",
        "only-web-and-mobile": "Solo aplicaciones web y móviles:",
        "includes": "Todo lo que incluye la versión Empresa Básico y además:",
        "standard-list": "<li>Versiones web de Word, Excel, PowerPoint y Outlook</li><li>Seminarios web con informes y registros de asistentes</li><li>Áreas de trabajo colaborativas para crear de forma conjunta con Microsoft Loop</li><li>Herramientas de edición y diseño de vídeo con Microsoft Clipchamp</li><li>Microsoft 365 Copilot está disponible como complemento</li>",
        "secure-services-2": "Servicios seguros en la nube y aplicaciones de escritorio, web y móviles:",
        "includes2": "Todo lo que incluye la versión Empresa Básico y además:",
        "includes3": "Todo lo que incluye la versión Empresa Estándar y además:",
        "includes4": "Todo lo que incluye la versión Empresa Estándar y además:",
        "includes5": "Todo lo que incluye la versión Empresa Estándar y además:",
        "includes6": "Todo lo que incluye la versión Empresa Estándar y además:",
        "premium-list": "<li>Administración de identidad y acceso avanzada</li><li>Protección mejorada frente a ciberamenazas contra virus y ataques de phishing</li><li>Protección de dispositivos y puntos de conexión de grado empresarial</li><li>Descubre, clasifica y protege información confidencial</li><li>Microsoft 365 Copilot está dispnible como complemento</li>",
        "application-list": "<li>Versiones web de Word, Excel, PowerPoint y Outlook</li><li>1 TB de almacenamiento en la nube por usuario</li><li>Soporte ininterrumpido por teléfono y a través de la Web</li><li>Microsoft 365 Copilot está disponible como complemento</li>",
        /*Office*/
        "mstecs-features-title-office": "PLANES EMPRESARIAL",
        "without-teams-1": "Sin Teams",
        "without-teams-2": "Sin Teams",
        "without-teams-3": "Sin Teams",
        "e1-list": "<li>Microsoft 365 en la Web con permisos de creación y edición para las versiones online de las Aplicaciones de Microsoft 365 principales.</li><li>Correo electrónico, almacenamiento y uso compartido de archivos.</li><li>1 TB de almacenamiento en la nube de OneDrive.</li><li>Soporte ininterrumpido por teléfono y a través de la Web.</li><li>Microsoft 365 Copilot está disponible como complemento</li>",
        "e3-list": "<li>Puedes instalar Aplicaciones de Microsoft 365 en hasta cinco equipos PC o Mac, cinco tabletas y cinco dispositivos móviles.</li><li>Cifrado de mensajes.</li><li>Administración de derechos.</li><li>Prevención de pérdida de datos para correo electrónico y archivos.</li><li>Microsoft 365 Copilot está disponible como complemento.</li>",
        "e5-list": "<li>Capacidades avanzadas de seguridad y cumplimiento.</li><li>Análisis de negocios escalable con Power BI.</li><li>Microsoft 365 Copilot está disponible como complemento.</li>",
        /* Google */
        "business-starter": "<li>30 GB de almacenamiento conjunto por usuario*</li><li>Correo electrónico empresarial personalizado y seguro del tipo tú@tu-empresa.com<li><li>Asistente de IA de Gemini en Gmail**</li><li>Chatea con la IA en la app de Gemini**</li><li>Videoconferencias de 100 participantes</li><li>Controles de seguridad y administración</li><li>Soporte técnico 24/7</li>",
        "business-standard": "<li>2 TB de almacenamiento conjunto por usuario*</li><li>Correo electrónico empresarial personalizado y seguro del tipo tú@tu-empresa.com</li><li>Asistente de IA de Gemini en Gmail, Documentos, Meet y más**</li><li>Chatea con la IA en la app de gemini y crea tu equipo de expertos de IA**</li><li>Asistente de investigación basado en IA (NotebookLM Plus)</li><li>Videoconferencias de 150 participantes, grabación y cancelación de ruido</li><li>Firma electrónica en Documentos y archivos PDF</li><li>Páginas de reservas de citas</li><li>Creador y editor de videos colaborativos</li><li>Diseños y combinación de correos electrónicos</li><li>Controles de seguridad y administración</li>",
        "business-plus": "<li>5 TB de almacenamiento conjunto por usuario*</li><li>Correo electrónico empresarial personalizado y seguro, detección electrónica, retención y S/MIME</li><li>Asistente de IA de Gemini en Gmail, Documentos, Meet y más**</li><li>Chatea con la IA en la app de Gemini y crea tu equipo de expertos de IA**</li><li>Asistente de investigación basado en IA (NotebookLM Plus)</li><li>Videoconferencias de 500 participantes, grabación, seguimiento de la asistencia y cancelación de ruido</li><li>Firma electrónica en Documentos y archivos PDF</li><li>Páginas de reservas de citas</li><li>Creador y editor de videos colaborativos</li><li>Diseños y combinación de correos electrónicos</li><li>Seguridad y controles de administración mejorados, incluidos Vault y administración avanzada de extremos</li>",
        "enterprise-applications": "<li>5 TB de almacenamiento conjunto por usuario*</li><li>Correo electrónico empresarial personalizado y seguro, detección electrónica, retención y S/MIME</li><li>Asistente de IA de Gemini en Gmail, Documentos, Meet y más**</li><li>Chatea con la IA en la app de Gemini y crea tu equipo de expertos de IA**</li><li>Asistente de investigación basado en IA (NotebookLM Plus)</li><li>Videoconferencias de 1,000 participantes, grabación, seguimiento de la asistencia, cancelación de ruido y transmisión en vivo dentro del dominio</li><li>Firma electrónica en Documentos y archivos PDF</li><li>Páginas de reservas de citas</li><li>Creador y editor de videos colaborativos</li><li>Diseños y combinación de correos electrónicos</li><li>Controles de seguridad, administración y cumplimiento avanzados, incluidos Vault, DLP, regiones de datos y administración empresarial de extremos</li><li>Asistencia mejorada***</li>",
        "communicatewithus": "Comunícate con Ventas para conocer los precios",
        /* Azure */
        "azure-desc": "Obtén asesoramiento individualizado sobre los precios de Azure",
        "price-calculator": "Calculadora de precios",
        "price-calculator-desc": "Configura productos de Azure y calcula sus costes.",
        "price-calculator-btn": "Explorar información",
        "tco": "Calculadora del coste total de propiedad (TCO)",
        "tco-desc": "Estima tu ahorro de costes al mover tus cargas de trabajo a Azure.",
        "tco-btn": "Información adicional",
        "questions": "Preguntas más frecuentes sobre los precios de Azure",
        "questions-desc": "Obtén respuestas a algunas preguntas frecuentes sobre los precios de Azure.",
        "questions-btn": "Preguntas frecuentes",
        "business-case": "Crear tu caso de negocio",
        "business-case-desc": "Crea tu caso de negocio en la nube de forma satisfactoria con indicaciones financieras y técnicas clave de Azure.",
        "business-case-btn": "Empezar",
        "azure-partner": "Ponte en contacto con un partner de Azure",
        "azure-partner-desc": "Obtén ayuda con los precios de Azure de un partner experto de Azure.",
        "azure-partner-btn": "Contacta un partner",
        "development": "Recursos para estudiantes de desarrollo",
        "development-desc": "Obtén información sobre las herramientas de desarrollo y las tecnologías en la nube, participa en la comunidad tecnológica y empieza a crear soluciones en la nube.",
        "development-btn": "Información adicional"

    },
    "en": {
        "we-are-button": "We are",
        "partners-button": "Partners",
        "services-button": "Our services",
        "certifications-button": "Certifications",
        "contact-button": "Contact",
        "ctechs-hero-title": "Leaders",
        "ctechs-hero-subtitle": "in cloud technologies",
        "ctechs-hero-description": "Responsibility Honesty Perseverance",
        "ctechs-hero-secondslide-firsttitle": "instructors",
        "ctechs-hero-secondslide-secondtitle": "support",
        "ctechs-hero-secondslide-thirdtitle": "certifications",
        "whoweare-title": "who . we . are",
        "whoweare-desc": "CTECH-S is a company with more than 10 years in the market dedicated to providing training and consulting services and solutions based on cloud platforms such as Amazon Web Services, Google Cloud Partner and CompTIA.<br><br>Looking to contribute to the technological development of each company, we have a team of highly trained and certified engineers and trainers.",
        "ourbenefits-title": "our <strong>benefits</strong>",
        "personel-text": "<strong>Staff specialized</strong><br>in assignment and calendar management",
        "attention-text": "<strong>Personalized attention</strong><br>at management level",
        "specialists-text": "<strong>Assigned specialists</strong><br>to address your clients inquiries",
        "acquisition": "<strong class='span-blue'>Acquisition renovation</strong><br>plan for new and existing <strong class='span-blue'>certifications</strong> on the market",
        "real-time": "<strong class='span-blue'>Real time</strong><br>support team assigned to every session",
        "dedicated": "<strong class='span-blue'>Dedicated learning & development</strong><br>process of andragogy skills for every instructor",
        "continous": "<strong class='span-blue'>Continous training</strong><br>regarding tools and training platforms",
        "high-adaptability": "<strong class='span-blue'>High adaptability</strong><br>to new platforms methodologies processes and internal corporate tools",
        "contactus-title": "Contact us",
        "contact-name-placeholder": "Your Name",
        "contact-email-placeholder": "Your Email",
        "contact-phone-placeholder": "Phone",
        "send-request": "Send Request",
        "partners": "<strong>partners</strong>",
        "partners-text": "We offer specialized instructors to training centers<br> & learning partners around the world.",
        "services-title": "our <strong>services</strong>",
        "services-highligth": "We have <strong class='text-color-orange'>the best technology</strong> <span class='text-biggest'>&</span> <strong class='text-color-blue'>certified consultants</strong> to offer you quality services.",
        "training-title": "Training",
        "training-desc": "We have native instructors and experts in different languages, such as English, Spanish, French, Portuguese and others. Backed up by ten years in the market, all of our trainers are certified.",
        "consulting-title": "Consulting",
        "consulting-desc": "We offer training solutions given by experts in the technological field that helps the company and its employees to improve their technical skills.",
        "managed-title": "Managed Services",
        "managed-desc": "We offer desktop, server and device client management solutions that help our clients reduce the complexity of infrastructure management a well as administrative services, accelerating the return on investment and providing resources that will ensure the correct management of Cloud services.",
        "cloud-title": "Cloud Implementation",
        "cloud-desc": "We offer cloud services consultation, administration and implementation, facilitating our clients' platforms, using state-of-the-art technologies that position us as leaders in the market.",
        "certifications-title": "<strong>Certifications</strong>",
        "mstecs-header-contact": "Contact",
        "callus": "Call us<br> +52 449 284 1532",
        "mailus": "Mail us<br> correo@mstecs.com",
        "mstecs-hero-title": "Leaders in technology",
        "mstecs-hero-list-item1": "Sales",
        "mstecs-hero-list-item2": "Licensing",
        "mstecs-hero-list-item3": "Consulting",
        "mstecs-hero-list-item4": "Managed services",
        "mstecs-hero-list-item5": "Global presence",
        "mstecs-licensing-title": "Licensing",
        "mstecs-licensing-subtitle": "Optimize your growth with our options",
        "m365desc": "Access the best collaborative work tools, cloud storage, and more. Licenses at special prices.",
        "business-plan-btn": "Business Plan",
        "smb-plan-btn": "SMB Plans",
        "googledesc": "Empower your infrastructure with scalable, secure, and flexible solutions. Licenses available at competitive prices.",
        "plan-prices-btn": "See plans and prices",
        "plan-prices-btn2": "See plans and prices",
        "plan-prices-btn3": "See plans and prices",
        "azuredesc": "Get scalability, security, and flexibility in the cloud. Transform your business today.",
        "awsdesc": "Leading cloud services to scale, innovate, and protect your company with flexible and secure solutions.",
        "mstecs-services-title": "Services",
        "mstecs-services-subtitle": "We are Microsoft partners so our trainers are highly qualified.",
        "mstecs-allies-title": "Our allies",
        "mstecs-features-title-microsoft": "SMB PLANS",
        "application": "APPLICATIONS",
        "basic": "Basic Business",
        "standard": "Standard Business",
        "premium": "Premium Business",
        "for-busisness": "for business",
        "from": "FROM",
        "from2": "FROM",
        "from3": "FROM",
        "from4": "FROM",
        "per-user": "per user/month",
        "per-user2": "per user/month",
        "per-user3": "per user/month",
        "per-user4": "per user/month",
        "anual-month": "(Annual and monthly plans tailored to your needs)",
        "anual-month2": "(Annual and monthly plans tailored to your needs)",
        "anual-month3": "(Annual and monthly plans tailored to your needs)",
        "anual-month4": "(Annual and monthly plans tailored to your needs)",
        "quote": "Contact sales",
        "quote2": "Contact sales",
        "quote3": "Contact sales",
        "quote4": "Contact sales",
        "app-first-start": "Applications and services to get your business up and running, including:",
        "basic-list": "<li>Identity, access, and user management for up to 300 employees</li><li>Personalized business email (you@yourbusiness.com)</li><li>Web and mobile versions of Word, Excel, PowerPoint, and Outlook</li><li>Chats, calls, and video conferences with Microsoft Teams</li><li>1 TB of cloud storage per employee</li><li>Over 10 additional apps for your business needs (Microsoft Bookings, Planner, Forms, and others)</li><li>Automatic spam and malware filtering</li><li>24/7 support by phone and web</li><li>Microsoft 365 Copilot is available as an add-on</li>",
        "secure-services": "Secure cloud services:",
        "only-web-and-mobile": "Web and mobile applications only:",
        "includes": "Everything included in the Basic Busisness version and more:",
        "standard-list": "<li>Web versions of Word, Excel, PowerPoint, and Outlook</li><li>Webinars with attendee reports and registrations</li><li>Collaborative workspaces to co-create with Microsoft Loop</li><li>Video editing and design tools with Microsoft Clipchamp</li><li>Microsoft 365 Copilot is available as an add-on</li>",
        "secure-services-2": "Secure cloud services and desktop, web and mobile applications:",
        "includes2": "Everything included in the Basic Enterprise version and more:",
        "includes3": "Everything included in the Standard Enterprise version and more:",
        "includes4": "Everything included in the Standard Enterprise version and more:",
        "includes5": "Everything included in the Standard Enterprise version and more:",
        "includes6": "Everything included in the Standard Enterprise version and more:",
        "premium-list": "<li>Advanced identity and access management</li><li>Enhanced protection against cyber threats such as viruses and phishing attacks</li><li>Enterprise-grade device and endpoint protection</li><li>Discover, classify, and protect sensitive information</li><li>Microsoft 365 Copilot is available as an add-on</li>",
        "application-list": "<li>Web versions of Word, Excel, PowerPoint, and Outlook</li><li>1 TB of cloud storage per user</li><li>24/7 support by phone and web</li><li>Microsoft 365 Copilot is available as an add-on</li>",
        /* Office Site*/
        "mstecs-features-title-office": "BUSINESS PLANS",
        "without-teams-1": "Without Teams",
        "without-teams-2": "Without Teams",
        "without-teams-3": "Without Teams",
        "e1-list": "<li>Microsoft 365 on the Web with creation and editing permissions for the online versions of the main Microsoft 365 Apps.</li><li>Email, file storage, and sharing.</li><li>1 TB of OneDrive cloud storage.</li><li>24/7 support by phone and web.</li><li>Microsoft 365 Copilot is available as an add-on.</li>",
        "e3-list": "<li>You can install Microsoft 365 Apps on up to five PCs or Macs, five tablets, and five mobile devices.</li><li>Message encryption.</li><li>Rights management.</li><li>Data loss prevention for email and files.</li><li>Microsoft 365 Copilot is available as an add-on.</li>",
        "e5-list": "<li>Advanced security and compliance capabilities.</li><li>Scalable business analytics with Power BI.</li><li>Microsoft 365 Copilot is available as an add-on.</li>",
        /* Google */
        "business-starter": "<li>30 GB of pooled storage per user*</li><li>Personalized and secure business email like you@your-company.com</li><li>Gemini AI assistant in Gmail**</li><li>Chat with AI in the Gemini app**</li><li>Video meetings with up to 100 participants</li><li>Security and admin controls</li><li>24/7 support</li>",
        "business-standard": "<li>2 TB of pooled storage per user*</li><li>Personalized and secure business email like you@your-company.com</li><li>Gemini AI assistant in Gmail, Docs, Meet, and more**</li><li>Chat with AI in the Gemini app and create your team of AI experts**</li><li>AI-powered research assistant (NotebookLM Plus)</li><li>Video meetings with up to 150 participants, recording, and noise cancellation</li><li>Electronic signature in Docs and PDF files</li><li>Appointment booking pages</li><li>Collaborative video creator and editor</li><li>Email layouts and mail merge</li><li>Security and admin controls</li>",
        "business-plus": "<li>5 TB of pooled storage per user*</li><li>Personalized and secure business email, eDiscovery, retention, and S/MIME</li><li>Gemini AI assistant in Gmail, Docs, Meet, and more**</li><li>Chat with AI in the Gemini app and create your team of AI experts**</li><li>AI-powered research assistant (NotebookLM Plus)</li><li>Video meetings with up to 500 participants, recording, attendance tracking, and noise cancellation</li><li>Electronic signature in Docs and PDF files</li><li>Appointment booking pages</li><li>Collaborative video creator and editor</li><li>Email layouts and mail merge</li><li>Enhanced security and admin controls, including Vault and advanced endpoint management</li>",
        "enterprise-applications": "<li>5 TB of pooled storage per user*</li><li>Personalized and secure business email, eDiscovery, retention, and S/MIME</li><li>Gemini AI assistant in Gmail, Docs, Meet, and more**</li><li>Chat with AI in the Gemini app and create your team of AI experts**</li><li>AI-powered research assistant (NotebookLM Plus)</li><li>Video meetings with up to 1,000 participants, recording, attendance tracking, noise cancellation, and live streaming within the domain</li><li>Electronic signature in Docs and PDF files</li><li>Appointment booking pages</li><li>Collaborative video creator and editor</li><li>Email layouts and mail merge</li><li>Advanced security, admin, and compliance controls, including Vault, DLP, data regions, and enterprise endpoint management</li><li>Enhanced support***</li>",
        "communicatewithus": "Contact Sales for pricing information",
        /* Azure */
        "azure-desc": "Get personalized advice on Azure pricing",
        "price-calculator": "Price calculator",
        "price-calculator-desc": "Configure Azure products and calculate their costs.",
        "price-calculator-btn": "Explore information",
        "tco": "Total Cost of Ownership (TCO) Calculator",
        "tco-desc": "Estimate your cost savings by moving your workloads to Azure.",
        "tco-btn": "Additional information",
        "questions": "Most frequently asked questions about Azure pricing",
        "questions-desc": "Get answers to some frequently asked questions about Azure pricing.",
        "questions-btn": "Frequently asked questions",
        "business-case": "Create your business case",
        "business-case-desc": "Successfully create your cloud business case with key financial and technical guidance from Azure.",
        "business-case-btn": "Get started",
        "azure-partner": "Contact an Azure partner",
        "azure-partner-desc": "Get help with Azure pricing from an expert Azure partner.",
        "azure-partner-btn": "Contact a partner",
        "development": "Resources for development students",
        "development-desc": "Learn about development tools and cloud technologies, participate in the tech community, and start building cloud solutions.",
        "development-btn": "Additional information"
    }
};

function changeLanguage(lang) {
    document.documentElement.lang = lang;

    for (const [id, text] of Object.entries(translations[lang])) {
        const element = document.getElementById(id);
        if (element) {
            if (element.tagName === 'INPUT' || element.tagName === 'TEXTAREA') {
                element.placeholder = text;
            } else {
                element.innerHTML = text;
            }
        }
    }

    localStorage.setItem('preferredLanguage', lang);
}

function loadLanguage() {
    const savedLanguage = localStorage.getItem('preferredLanguage');

    if (savedLanguage && translations[savedLanguage]) {
        document.getElementById('language-select').value = savedLanguage;
        changeLanguage(savedLanguage);
        console.log("language-loader.js loaded successfully");
    } else {
        changeLanguage('es');
    }
}

document.addEventListener('DOMContentLoaded', function () {
    document.getElementById('language-select').addEventListener('change', function () {
        changeLanguage(this.value);
    });

    loadLanguage();
});
